spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    topic:
      name: "wikimedia.recentchange"
    streams:
      application-id: "wikimedia-stats-application"